# Config file for TimeCommander by LDX;

# List of commands for the plugin to execute at the given times;
# Command: Command to execute;
# Time: Amount of time in minutes between command executions;
Messages:
  - Message: Plugin by NycuRO!
    Time: 5
  - Message: Test Plugin!
    Time: 10
